### ISSUE TITLE
Enter not triggering screenshot in normal screenshot view, only in thumb view

### ISSUE THREAD

**Issue by mbloomfi** [qualtrics-themes-team/qualtrics-theme-suite-app#3]

**Comment by mbloomfi** [comment]
Only happened once. It was like the cursor was stuck in the text editor, and enter was just making line breaks there.

**Comment by samueleaton** [comment]
Ok. I have notices that if you are focused on the text editor, it will not take a picture. I will change it to de-focus on the editor if you go to screenshot or thumbnail mode.

**Comment by samueleaton** [comment]
Escape now exits `screenshot` and `thumbnail` mode. Also, the code editor will lose focus when enabling `screenshot` or `thumbnail` mode, so any key presses while taking a screenshot will not affect the code.
